import "@/styles/globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeProvider";
import NavMenu from "@/components/fragments/NavMenu";
import { UIContextProvider } from "@/context/UIContext";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <UIContextProvider>
            <NavMenu />
            <main>{children}</main>
          </UIContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
