"use client";

import "@/styles/globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeProvider";
import NavMenu from "@/components/fragments/NavMenu";
import Loading from "@/components/ui/loading";
import { useEffect, useState } from "react";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    const interval = setInterval(() => {
      setIsLoading(false);
    }, 3000);
  
    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {isLoading ? (
            <Loading />
          ) : (
            <>
              <NavMenu />
              <main className={`transition-opacity ${isLoading ? 'opacity-0' : 'opacity-100'}`}>{children}</main>
            </>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
